name: Add PR to project
on:
  pull_request:
    types:
      - opened
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get NDAO eng project data
        env:
          GITHUB_TOKEN: ${{ secrets.ENDAOMENT_AUTO_ADDER }}
          ORGANIZATION: endaoment
          PROJECT_NUMBER: 16
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV

      - name: Add PR to NDAO eng project
        env:
          GITHUB_TOKEN: ${{ secrets.ENDAOMENT_AUTO_ADDER }}
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID -f --jq '.data.addProjectV2ItemById.projectV2Item.id')"     

      - name: Add PR to NDAO eng project
        env:
          GITHUB_TOKEN: ${{ secrets.ENDAOMENT_AUTO_ADDER }}
          PR_ID: ${{ github.event.pull_request.node_id }}
          LABEL: "*new*"
        run: |
         item_id="$( gh api graphql -f query='
            mutation($label:ID!, $pr:ID!) {
              addLabelsToLabelable(input: {labelIds: [$label], labelableId: $pr}) {
                item {
                  id
                }
              }
            }' -f pr=$PR_ID -f label=$label --jq '.data.addLabelsToLabelable.item.id')"     