name: Add issue to project
on:
  issues:
    types:
      - opened

jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get NDAO eng project data
        env:
          GITHUB_TOKEN: ${{ secrets.ENDAOMENT_AUTO_ADDER }}
          ORGANIZATION: endaoment
          PROJECT_NUMBER: 16
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER -f > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
                    
      - name: Add issue to NDAO eng project
        env:
          GITHUB_TOKEN: ${{ secrets.ENDAOMENT_AUTO_ADDER }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          LABELS: "['*new*']"
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID -f labels=$LABELS --jq '.data.addProjectV2ItemById.projectV2Item.id')"   
        |
         item_id="$( gh api graphql -f query='
            mutation($labels:[ID!], $pr:ID!) {
              addLabelsToLabelable(input: {labelIds: $labels, labelableId: $pr}) {
                item {
                  id
                }
              }
            }' -f pr=$PR_ID -f labels=$labels --jq '.data.addLabelsToLabelable.item.id')"            

