name: Add PR to project
on:
  pull_request:
    types:
      - opened
      - push

env: 
  GITHUB_TOKEN: ${{ secrets.ENDAOMENT_AUTO_ADDER }}
  ORGANIZATION: endaoment
  PROJECT_NUMBER: 16
  PR_ID: ${{ github.event.pull_request.node_id }}
  LABELS: "[*new*]"

jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get NDAO eng project data
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -f number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV

      - name: Add PR to NDAO eng project
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
                item {
                  id
                }
              }
            }' -f pr={{ env.PROJECT_ID }} -f project={{ env.PROJECT_ID }} 

      - name: Add *new* tag to PR
        run: |
          gh api graphql -f query='
            mutation ($labels:[ID!]!, $pr:ID!) {
              addLabelsToLabelable(input: {labelIds: ${{ env.LABELS }}, labelableId: ${{ env.PR_ID }} }) {
                clientMutationId
              }
            }' -f labels=${{env.LABELS}} -f pr={{env.PR_ID}}